# Generated by Django 6.0.3 on 2026-03-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_created_at_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.medicine')),
            ],
        ),
    ]
