# Generated by Django 6.0.3 on 2026-03-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_medicine_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medicine'),
        ),
    ]
