# Generated by Django 6.0.3 on 2026-03-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stock_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.medicine'),
        ),
    ]
